name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: one
        uses: actions/checkout@v2
      - name: two
        run: env | sort
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: one
        uses: actions/checkout@v2
      - name: two
        run: echo Hello        
  job3:
     name: third job
     runs-on: macos-latest
     steps:
       - name: one
         uses: actions/checkout@v2
       - name: two
         run: env | sort
  job4:
    needs: [job1,job2,job3]
    name: forth job
    runs-on: ubuntu-latest
    steps:
      - name: one
        uses: actions/checkout@v2
      - name: two
        run: env | sort     
